version: '3.8'

services:
  regression:
    build: .
    volumes:
      - ./allure-report:/app/allure-report
      - ./allure-results:/app/allure-results
    command: /bin/sh -c "npm test && npm run report:generate"
